file_format: "1"
id: kaldera
name: kaldera
type: shield
url: https://github.com/KrishPatel1404/kaldera-zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - kaldera_left
  - kaldera_right
